name: CI

# Status badge for README
# [![CI](https://github.com/${{ github.repository }}/actions/workflows/main.yml/badge.svg)](https://github.com/${{ github.repository }}/actions/workflows/main.yml)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Install dependencies
      run: |
        npm install -g npm@latest
        npm ci
      
    - name: Run unit tests with coverage
      run: npm run test:ci
      
    - name: Build application
      run: npm run build
      
    - name: Install Cypress
      run: npx cypress install
        
    - name: Start app and run Cypress tests
      run: |
        npm start & npx wait-on http://localhost:3000
        npm run test:e2e
      env:
        CYPRESS_RECORD: false
    
    - name: Upload coverage reports
      if: always()
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        fail_ci_if_error: false

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.node-version }}
        path: |
          coverage/
          cypress/videos/
          cypress/screenshots/
        if-no-files-found: ignore 